In [20]:
!pip install numpy


[notice] A new release of pip available: 22.2.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.2/62.2 MB 6.6 MB/s eta 0:00:00:00:0100:01

[notice] A new release of pip available: 22.2.1 -> 24.0
[notice] To update, run: pip install --upgrade pip


In [ ]:
!pip install opencv-python

In [22]:
!pip install keras

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 10.0 MB/s eta 0:00:0000:010:01
  Using cached rich-13.7.1-py3-none-any.whl (240 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 38.3 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.2/311.2 kB 36.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 40.0 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.7/133.7 kB 16.3 MB/s eta 0:00:00
  Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
  Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)

[notice] A new release of pip available: 22.2.1 -> 24.0
[notice] To update, run: pip install --upgrade pip


In [24]:
!pip install tensorflow

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 589.8/589.8 MB 3.1 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 11.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.5/24.5 MB 16.1 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 15.4 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 11.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 19.0 MB/s eta 0:00:0000:0100:01
  Using cached requests-2.32.3-py3-none-any.whl (64 kB)
  Using cached protobuf-4.25.3-cp37-abi3-manylinux2014_x86_64.whl (294 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 16.9 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.3/80.3 kB 10.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 17.4 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.8/65.8 kB 14.8 MB/s eta 0:00:00
  Using 

In [26]:
!pip install scikit-learn

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.3/13.3 MB 37.6 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 301.8/301.8 kB 31.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 4.3 MB/s eta 0:00:0000:0100:01m

[notice] A new release of pip available: 22.2.1 -> 24.0
[notice] To update, run: pip install --upgrade pip


In [29]:
!pip install matplotlib

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 25.6 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 39.3 MB/s eta 0:00:0000:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.2/103.2 kB 21.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 2.4 MB/s eta 0:00:0000:0100:01m
  Using cached pillow-10.3.0-cp310-cp310-manylinux_2_28_x86_64.whl (4.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 305.2/305.2 kB 4.3 MB/s eta 0:00:00a 0:00:01

[notice] A new release of pip available: 22.2.1 -> 24.0
[notice] To update, run: pip install --upgrade pip


In [6]:
!pip install google-cloud-storage


[notice] A new release of pip available: 22.2.1 -> 24.0
[notice] To update, run: pip install --upgrade pip


In [4]:
!pip install scikit-learn


[notice] A new release of pip available: 22.2.1 -> 24.0
[notice] To update, run: pip install --upgrade pip


In [1]:
import numpy as np
import cv2
from os import listdir
from keras.preprocessing import image
from keras.preprocessing.image import img_to_array
from sklearn.preprocessing import LabelBinarizer
from sklearn.preprocessing import MultiLabelBinarizer
import pickle
from sklearn.model_selection import train_test_split
#from keras.preprocessing.image import ImageDataGenerator
import keras
from keras.datasets import cifar10
from keras import backend as K
import matplotlib
from matplotlib import pyplot as plt

2024-06-05 11:17:47.802564: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-06-05 11:17:47.803033: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-05 11:17:47.808264: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-05 11:17:47.839567: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-05 11:17:48.451670: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warnin

# Importing the Data 

In [2]:
# Imports
import os
from predicting_nails.params import *
from predicting_nails.prediction.get_data import get_simple_data, load_simple_data
from PIL import Image

In [3]:
# Get resized (224,224,3) and labeled (0,1) data from your local directory for the simple model

nb_healthy = 50     #defines the number of healthy images to be downloaded and loaded
nb_disease = 50     #defines the number of diseased images to be downloaded and loaded

if os.path.exists(os.path.join(LOCAL_DATA_PATH, "dataset_for_model_1")) == False:
    get_simple_data(nb_healthy = nb_healthy, nb_disease = nb_disease)
    X, y = load_simple_data(LOCAL_DATA_PATH, nb_healthy = nb_healthy, nb_disease = nb_disease)
else:
    X, y = load_simple_data(LOCAL_DATA_PATH, nb_healthy = nb_healthy, nb_disease = nb_disease)

Copying gs://predicting-nail-diseases/dataset_for_model_1/healthy_data/healthy_0.JPG...
/ [1 files][ 49.0 KiB/ 49.0 KiB]                                                
==> NOTE: You are performing a sequence of gsutil operations that may
run significantly faster if you instead use gsutil -m cp ... Please
see the -m section under "gsutil help options" for further information
about when gsutil -m can be advantageous.


Operation completed over 1 objects/49.0 KiB.                                     
Copying gs://predicting-nail-diseases/dataset_for_model_1/healthy_data/healthy_1.JPG...
/ [1 files][785.9 KiB/785.9 KiB]                                                
==> NOTE: You are performing a sequence of gsutil operations that may
run significantly faster if you instead use gsutil -m cp ... Please
see the -m section under "gsutil help options" for further information
about when gsutil -m can be advantageous.


Operation completed over 1 objects/785.9 KiB.                             

In [5]:
X[1]    # Images

array([[[144, 134, 125],
        [137, 127, 118],
        [134, 124, 115],
        ...,
        [170, 142, 128],
        [182, 154, 140],
        [188, 160, 146]],

       [[135, 125, 115],
        [131, 122, 113],
        [135, 125, 116],
        ...,
        [171, 143, 129],
        [181, 153, 139],
        [186, 158, 144]],

       [[124, 113, 104],
        [130, 119, 110],
        [141, 130, 121],
        ...,
        [176, 148, 134],
        [182, 154, 140],
        [184, 156, 142]],

       ...,

       [[ 98,  21,  37],
        [ 99,  22,  38],
        [ 96,  20,  36],
        ...,
        [130,  80,  75],
        [124,  73,  69],
        [130,  79,  75]],

       [[ 97,  20,  36],
        [ 98,  21,  37],
        [ 98,  21,  37],
        ...,
        [134,  84,  79],
        [130,  80,  76],
        [136,  85,  81]],

       [[ 96,  18,  34],
        [ 97,  20,  36],
        [ 99,  21,  37],
        ...,
        [137,  88,  83],
        [135,  86,  81],
        [138,  89,  84]]

In [10]:
y       # Classsification (Healthy=0, Disease=1)

array([1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1])

# Creating a Training and Testing Set

In [6]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Print the shapes of the resulting datasets
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (80, 224, 224, 3)
X_test shape: (20, 224, 224, 3)
y_train shape: (80,)
y_test shape: (20,)


# Normalization of Pixel Values

In [11]:
X_train = X_train / 255.0
X_test = X_test / 255.0

In [13]:
X_train[1]

array([[[0.48235294, 0.4745098 , 0.49411765],
        [0.48627451, 0.48235294, 0.50196078],
        [0.48627451, 0.47843137, 0.49803922],
        ...,
        [0.49803922, 0.49019608, 0.49411765],
        [0.50588235, 0.49411765, 0.50196078],
        [0.50980392, 0.49411765, 0.49803922]],

       [[0.48235294, 0.4745098 , 0.48627451],
        [0.48235294, 0.4745098 , 0.49411765],
        [0.48627451, 0.47843137, 0.49411765],
        ...,
        [0.49411765, 0.48627451, 0.49019608],
        [0.49803922, 0.49019608, 0.49803922],
        [0.50980392, 0.49411765, 0.49803922]],

       [[0.48235294, 0.4745098 , 0.48627451],
        [0.48235294, 0.4745098 , 0.48627451],
        [0.48627451, 0.47843137, 0.49019608],
        ...,
        [0.49019608, 0.48627451, 0.49411765],
        [0.49411765, 0.49019608, 0.49803922],
        [0.49411765, 0.49019608, 0.49411765]],

       ...,

       [[0.39215686, 0.39215686, 0.4       ],
        [0.39215686, 0.39607843, 0.40392157],
        [0.39215686, 0

In [15]:
X_train[1].show()

AttributeError: 'numpy.ndarray' object has no attribute 'show'